POST http://localhost:4000/ HTTP/1.1
Content-Type: application/json

{
    "firstName":"anwar",
    "lastName":"tarek",
    "age":24,
    "email":"anwar@gmail.com"
}
#####
GET  http://localhost:4000/ HTTP/1.1
####
PATCH http://localhost:4000/6 HTTP/1.1
Content-Type: application/json

{
    "age":20
}
#####
DELETE http://localhost:4000/6 HTTP/1.1

####
POST http://localhost:4000/post HTTP/1.1
Content-Type: application/json

{
    "title":"post tarek",
    "user_id":1
}
####
POST  http://localhost:4000/post/many HTTP/1.1
Content-Type: application/json

[
    {
        "title":"test 3",
        "user_id":2,
        "active":true,
        "content":null
    },
    {
        "title":"test 4",
        "user_id":1,
        "active":true,
        "content":null
    }
]